In [15]:
!pip install https://github.com/p-koo/tfomics/tarball/master

  Using cached https://github.com/p-koo/tfomics/tarball/master


In [1]:
import tensorflow as tf

import numpy as np
import requests as rq
import io, h5py, os

from tfomics import moana, evaluate

In [2]:
data = rq.get('https://www.dropbox.com/s/c3umbo5y13sqcfp/synthetic_dataset.h5?raw=true')
data.raise_for_status()

with h5py.File(io.BytesIO(data.content), 'r') as dataset:
    x_train = np.array(dataset['X_train']).astype(np.float32).transpose([0, 2, 1])
    y_train = np.array(dataset['Y_train']).astype(np.float32)
    x_valid = np.array(dataset['X_valid']).astype(np.float32).transpose([0, 2, 1])
    y_valid = np.array(dataset['Y_valid']).astype(np.int32)
    x_test = np.array(dataset['X_test']).astype(np.float32).transpose([0, 2, 1])
    y_test = np.array(dataset['Y_test']).astype(np.int32)

In [3]:
directories = [i[0] for i in os.walk('models')][1:]
models = [i[2] for i in os.walk('models')][1:]

In [28]:
for i in range(len(directories)):
    print(i / len(directories) * 100)
    for j in range(len(models[i])):
        
        model = tf.keras.models.load_model(h5py.File(os.path.join(directories[i], models[i][j]), 'r'))
        
        ppms = moana.filter_activations(x_test, model, layer=3, window=20, threshold=5)
        ppms = moana.clip_filters(ppms, threshold=0.5, pad=3)
        
        if not os.path.exists(os.path.join('motifs', directories[i].split('\\')[1])):
            os.makedirs(os.path.join('motifs', directories[i].split('\\')[1]))
        
        moana.meme_generate(ppms, output_file=os.path.join('motifs', directories[i].split('\\')[1], models[i][j].split('.h5')[0] + '.meme'), prefix='filter')

0.0
[[[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 ...

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  ...
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]]
8.333333333333332


KeyboardInterrupt: 

In [6]:
model = tf.keras.models.load_model(h5py.File(os.path.join('models', 'kernels', 'model-19.h5'), 'r'))

print(model.layers[3].name)
model.evaluate(x_test, y_test)

activation_12
188/188 [==============================] - 13s 63ms/step - loss: 0.1709 - auroc: 0.9609 - aupr: 0.8654


[0.17087510228157043, 0.9608717560768127, 0.8654062747955322]