In [4]:
import requests as rq
import io
import numpy as np

In [5]:
response = rq.get('https://github.com/Rohan75/ConvolutionalAttention/blob/master/ConvolutionalAttentionNN/train_x.npy?raw=true')
response.raise_for_status()
data = io.BytesIO(response.content)
file = np.load(data, allow_pickle=True)
print(file)

[[[0 0 0 1]
  [0 1 0 0]
  [0 1 0 0]
  ...
  [1 0 0 0]
  [1 0 0 0]
  [1 0 0 0]]

 [[0 1 0 0]
  [0 0 1 0]
  [0 0 1 0]
  ...
  [0 1 0 0]
  [1 0 0 0]
  [1 0 0 0]]

 [[0 0 0 1]
  [0 1 0 0]
  [0 1 0 0]
  ...
  [0 0 1 0]
  [0 0 1 0]
  [0 0 1 0]]

 ...

 [[1 0 0 0]
  [1 0 0 0]
  [0 0 1 0]
  ...
  [0 1 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[1 0 0 0]
  [0 0 1 0]
  [0 0 0 1]
  ...
  [0 0 1 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[0 1 0 0]
  [0 1 0 0]
  [0 0 1 0]
  ...
  [0 0 0 1]
  [1 0 0 0]
  [0 0 1 0]]]
